-- CreateTable
CREATE TABLE "wallets" (
    "ID" SERIAL NOT NULL,
    "FULL_NAME" VARCHAR(100) NOT NULL,
    "CPF" BIGINT NOT NULL,
    "EMAIL" VARCHAR(100) NOT NULL,
    "PASSWORD" VARCHAR(100) NOT NULL,
    "TYPE" INTEGER NOT NULL,
    "BALANCE" DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    "VERSION" BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT "wallets_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "transactions" (
    "ID" SERIAL NOT NULL,
    "PAYER" INTEGER NOT NULL,
    "PAYEE" INTEGER NOT NULL,
    "VALUE" DECIMAL(65,30) NOT NULL,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "transactions_pkey" PRIMARY KEY ("ID")
);

-- CreateIndex
CREATE UNIQUE INDEX "wallets_CPF_key" ON "wallets"("CPF");

-- CreateIndex
CREATE UNIQUE INDEX "wallets_EMAIL_key" ON "wallets"("EMAIL");

-- AddForeignKey
ALTER TABLE "transactions" ADD CONSTRAINT "transactions_PAYER_fkey" FOREIGN KEY ("PAYER") REFERENCES "wallets"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "transactions" ADD CONSTRAINT "transactions_PAYEE_fkey" FOREIGN KEY ("PAYEE") REFERENCES "wallets"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;
