-- CreateTable
CREATE TABLE "WALLETS" (
    "ID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "FULL_NAME" TEXT NOT NULL,
    "CPF" BIGINT NOT NULL,
    "EMAIL" TEXT NOT NULL,
    "PASSWORD" TEXT NOT NULL,
    "TYPE" INTEGER NOT NULL,
    "BALANCE" DECIMAL NOT NULL DEFAULT 0.00,
    "VERSION" BIGINT NOT NULL
);

-- CreateTable
CREATE TABLE "TRANSACTIONS" (
    "ID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "PAYER" INTEGER NOT NULL,
    "PAYEE" INTEGER NOT NULL,
    "VALUE" DECIMAL NOT NULL,
    "CREATED_AT" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "TRANSACTIONS_PAYER_fkey" FOREIGN KEY ("PAYER") REFERENCES "WALLETS" ("ID") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "TRANSACTIONS_PAYEE_fkey" FOREIGN KEY ("PAYEE") REFERENCES "WALLETS" ("ID") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "WALLETS_CPF_key" ON "WALLETS"("CPF");

-- CreateIndex
CREATE UNIQUE INDEX "WALLETS_EMAIL_key" ON "WALLETS"("EMAIL");
